config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  root to: 'pages#welcome'

  get 'suggestions'    , to: 'pages#suggestions'    , as: 'suggestions'
  get 'intro', to: 'pages#intro', as: 'intro'

  get 'dashboard', to: 'dashboards#show',   as: 'dashboard'
  get 'graph',     to: 'user_graphs#show',  as: 'graph'
  get 'meetups',   to: 'user_meetups#show', as: 'meetups'

  resources :bookmarks, only: [:create, :destroy]

  devise_scope :user do
    get 'login',      to: 'omniauth_callbacks#authorize',      as: 'login'
    get 'my_profile', to: 'omniauth_callbacks#my_profile', as: 'my_profile'
    get 'accept',     to: 'omniauth_callbacks#accept',     as: 'accept'
    get 'profile',    to: 'omniauth_callbacks#profile',    as: 'profile'
  end
end

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
<div class="container-fluid">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "CareerCrumbs", root_path, class: "navbar-brand cc-title" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
        <% if !user_signed_in? %>
          <%= link_to "Log in", login_path %>
        <% end %>
        </li>
        <% if user_signed_in? %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle navpix" data-toggle="dropdown"><%= current_user.first_name %> <%= image_tag current_user.pic_url, class: "nav-photo" %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Dashboard", dashboard_path %></li>
            <li><%= link_to "Suggestions", suggestions_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>