config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  root to: 'pages#welcome'

  get 'suggestions'    , to: 'pages#suggestions'    , as: 'suggestions'
  get 'intro', to: 'pages#intro', as: 'intro'

  get 'dashboard', to: 'dashboards#show',   as: 'dashboard'
  get 'graph',     to: 'user_graphs#show',  as: 'graph'
  get 'meetups',   to: 'user_meetups#show', as: 'meetups'

  resources :bookmarks, only: [:create, :destroy]

  devise_scope :user do
    get 'login',      to: 'omniauth_callbacks#authorize',      as: 'login'
    get 'my_profile', to: 'omniauth_callbacks#my_profile', as: 'my_profile'
    get 'accept',     to: 'omniauth_callbacks#accept',     as: 'accept'
    get 'profile',    to: 'omniauth_callbacks#profile',    as: 'profile'
  end
end

app/views/pages/intro.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="intro-blip">
        Here's a look at how your Suggestions page will work. When you're ready, <%= link_to "View Suggestions", suggestions_path, class: "btn btn-primary btn-sm" %>
      </div>
      </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="suggested-job-head">Positions you may be interested in:</div>
      <div class="job-box">
        <div class="jobs-dashed-border">
          <p>Based on your LinkedIn profile,<br/> we'll show you some jobs you might like here.</p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="job-words">
        <div class="job-words-head">Skills required:</div>
        <div id="word-box">
          <div class="dashed-border">
            <p>Next, we'll run a text analysis on those jobs,<br/> and return the keywords that show up most often.</p>
          </div>
        </div>
      </div>

      <div class="meetup-groups">
        <div class="meetup-groups-head">Where to find those skills:</div>
        <div id="meetup-box">
          <div class="meetup-box">
            <div class="dashed-border">
              <p>For each of your keywords above,<br/> we'll show you one related Meetup group here.</p><br/>
              <p>Meetup groups can be great places to learn new<br/> skills and make new friends with those skills.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="container">
  <div class="profile-container">
    <h3>Welcome, <%= @user.first_name %></h3>
    <%= @user.first_name %>
    <%= @user.last_name %>
    <br/>
    <%= @user.headline %>
    <br/>
    <strong>Industry:</strong> <%= @user.industry %>
    <br/>
    <%= image_tag @user.pic_url %>
    <br/>
  </div>
</div>

app/views/pages/suggestions.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="intro-blip">
        Not sure what you're looking at? Learn more here: <%= link_to "About Suggestions", intro_path, class: "btn btn-primary btn-sm" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="suggested-job-head"><%= @user.jobs.count %> positions you may be interested in:</div>
      <% @user.jobs.each do |job| %>
        <div class="job-box">
          <span class="suggested-job-title"><%= job.title %></span><br/>
          <span class="suggested-job-company"><%= job.company %></span>
          <span class="suggested-job-loc">(<%= job.location %>)</span><br/>
          <span class="suggested-job-desc"><%= job.description %>...</span><br/><br/>
          <%= link_to "View on LinkedIn", 'https://www.linkedin.com/jobs2/view/' + job.linkedin_id.to_s, class: "btn btn-default btn-inline btn-joblink" %>
          <% if @user.bookmarks.includes?(job.id, job.class) %>
            <%= link_to "Bookmarked", bookmark_path(@user, bookmark: {user_id: @user.id, bookmarkable_id: job.id, bookmarkable_type: job.class}), method: :delete, class: "btn btn-success btn-unbookmark" %>
          <% else %>
            <%= link_to 'Bookmark', bookmarks_path(bookmark: {user_id: @user, bookmarkable_id: job.id, bookmarkable_type: job.class}), method: :post, class: "btn btn-default btn-inline btn-bookmark" %>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="col-md-6">
      <div class="job-words">
        <div class="job-words-head">Top words found in those positions:</div>
        <div id="word-box">
          <div id="word-box">
            <div style="text-align: center;"><%= image_tag "http://assets-edge.vacationhomerentals.com/design/images/loading_big.gif" %></div>
            <script>
              $(document).ready(function () {
                setTimeout(function()
                {
                  $("#word-box").load("/graph");
                }, 1500);
              });
            </script>
          </div>
        </div>
      </div>
      <div class="meetup-groups">
        <div class="meetup-groups-head">Suggested Meetup groups:</div>
        <div id="meetup-box">
          <div style="text-align: center; margin-top: 45px;"><%= image_tag "http://assets-edge.vacationhomerentals.com/design/images/loading_big.gif" %></div>
          <script>
            $(document).ready(function () {
              setTimeout(function()
              {
                $("#meetup-box").load("/meetups");
              }, 3000);
            });
          </script>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/welcome.html.erb
<body class="homebody">
  <div class="container">
    <div class="homepage">
      <br/><br/><br/>
      <div class="homepage-taste">Taste your future.</div>

      <br/><br/>
      <div class="homepage-btn"><%= link_to "Sign in with LinkedIn", login_path, class: "btn btn-lg btn-default" %></div>
    </div>
  </div>